### ISSUE TITLE
Capture handshakes for all networks?

### ISSUE THREAD

**Issue by Divide-By-0** [phenotypic/WiFiCrackPy#11]
Is there a way to capture handshakes for multiple networks at once?

**Comment by phenotypic** [comment]
Hi there, I would recommend using [`zizzania`](https://github.com/cyrus-and/zizzania) directly if you would like to capture handshakes for multiple networks.

This script is designed to capture and crack handshakes for one network at a time. It uses `zizzania`'s `-q` flag to achieve this by terminating `zizzania` once a full handshake has been captured for the target network.
