### ISSUE TITLE
Zizzania not found

### ISSUE THREAD

**Issue by McCloud94** [phenotypic/WiFiCrackPy#12]
Hi, getting this error: sudo: /Users/xxx/zizzania/src/zizzania: command not found

And another one, probably caused by the first one? 
FileNotFoundError: [Errno 2] No such file or directory: 'hcxpcapngtool'

**Comment by phenotypic** [comment]
Hi there, you are getting those errors because you have not installed the prerequisites correctly.

Please follow the installation instructions in the `Prerequisites` section of the `README`.
