### ISSUE TITLE
-d deauth not working? 

### ISSUE THREAD

**Issue by McCloud94** [phenotypic/WiFiCrackPy#13]
After I select a network from the list to target,  I get the following, but nothing else happens.

Select a network to crack: 17
Initiating zizzania to capture handshake...
[+] Waiting for traffic, press Ctrl-C to exit...
[+] BSS discovered 64:20:E0:FC:85:26 $'xxx'

I assumed that by using the -d (python3 WiFiCrackPy.py -d) it will deauth any users connected and doesn't need to wait.

I also tried to see if there are even any users connected to the network, but seems like the best tool for this, JamWifi is not available for M1 Macs.

While doing some research, someone else also claims the -d function doesn't do anything. 
https://www.reddit.com/r/hacking/comments/18zyrgs/comment/kgucyg1/?context=3

Thanks

**Comment by phenotypic** [comment]
Hi there, as mentioned in the README, there are compatibility issues when `zizzania` tries sending deauthentication frames on newer Macs (~2018 onwards, including M1 Macs). See [here](https://github.com/phenotypic/WiFiCrackPy/issues/3#issuecomment-1863898395) for more details.
