### ISSUE TITLE
Crash after start

### ISSUE THREAD

**Issue by trivarialthea** [phenotypic/WiFiCrackPy#15]
```
user@mac WiFiCrackPy % python3 WiFiCrackPy.py 

__          ___ ______ _  _____                _    _____       
\ \        / (_)  ____(_)/ ____|              | |  |  __ \      
 \ \  /\  / / _| |__   _| |     _ __ __ _  ___| | _| |__) |   _ 
  \ \/  \/ / | |  __| | | |    | '__/ _` |/ __| |/ /  ___/ | | |
   \  /\  /  | | |    | | |____| | | (_| | (__|   <| |   | |_| |
    \/  \/   |_|_|    |_|\_____|_|  \__,_|\___|_|\_\_|    \__, |
                                                           __/ |
                                                          |___/ 

Scanning for networks...

Password:
Traceback (most recent call last):
  File "/Users/user/Github/WiFiCrackPy/WiFiCrackPy.py", line 113, in <module>
    scan_networks()
  File "/Users/user/Github/WiFiCrackPy/WiFiCrackPy.py", line 36, in scan_networks
    bssid = re.search('([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})', ' '.join(scan[i])).group(0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

I have all the prerequesities installed and there are wifi networks present... Any idea why this happens?

**Comment by phenotypic** [comment]
Hi there, thank you for opening this issue.

With macOS 14.4, Apple has retired the `airport` command-line utility (see [here](https://www.intuitibits.com/2024/03/14/goodbye-airport/) for more information).

I am trying to work on a solution leveraging Apple's [CoreWLAN](https://developer.apple.com/documentation/corewlan) framework as described [here](https://clburlison.com/macos-wifi-scanning/), but there seem to be issues with the Python implementation in macOS 14.4 (see [here](https://forums.developer.apple.com/forums/thread/748518)).

**Comment by phenotypic** [comment]
I have migrated the script from `airport` to `CoreWLAN` in the latest version of the script.

Please re-clone the repository and install the new dependencies.

**Note:** Python must be granted location services permissions in order to scan networks.
