### ISSUE TITLE
can not get bssid

### ISSUE THREAD

**Issue by cmulittlechild** [phenotypic/WiFiCrackPy#16]
this is the error
<img width="1010" alt="image" src="https://github.com/phenotypic/WiFiCrackPy/assets/31565938/f45c4ac6-8d9e-4326-81d1-efdfdb98d50f">

i try to figure out, found that there is no bssid-can't get the MAC address.
<img width="1074" alt="image" src="https://github.com/phenotypic/WiFiCrackPy/assets/31565938/496a276b-5d40-4ef8-b2a3-aac7fb2e32b7">

this is my macos version
<img width="590" alt="image" src="https://github.com/phenotypic/WiFiCrackPy/assets/31565938/e2e5751d-c606-43fa-a59f-6fea9ce0eb94">

**Comment by dyerai** [comment]
Having the same issue

**Comment by phenotypic** [comment]
Hi there, thanks for opening this issue. Please can you confirm you get the following messages when starting the script:

```
Obtaining authorisation for location services (required for WiFi scanning)...

Received authorisation, continuing...
```

**Comment by phenotypic** [comment]
In the latest version of the script, I manually load the frameworks using `objc` rather than importing `CoreWLAN` and `CoreLocation` directly.

This seems to have resolved the issue on the other MacBook I have used for testing. Please confirm this has resolved the issue for you too.
