### ISSUE TITLE
Core WLAN

### ISSUE THREAD

**Issue by DQCEW1** [phenotypic/WiFiCrackPy#17]
WiFiCrackPy/WiFiCrackPy.py", line 1, in <module>
    import subprocess, re, argparse, CoreWLAN, CoreLocation
ModuleNotFoundError: No module named 'CoreWLAN'

**Comment by DQCEW1** [comment]
its macos

**Comment by phenotypic** [comment]
Hi there, please ensure you've installed the necessary dependencies:

```
pip3 install -r requirements.txt
```

It looks like you could be missing the `pyobjc` module at the moment.

**Comment by IISAKNIFE** [comment]
Same issue, all requirements satisfied

**Comment by phenotypic** [comment]
Are you still experiencing this issue? Please try updating your macOS version. Also check you have installed the necessary prerequisites and requirements. I am running on 14.4.1 without issue.

**Comment by phenotypic** [comment]
In the latest version of the script, I manually load the frameworks using `objc` rather than importing `CoreWLAN` and `CoreLocation` directly.

This seems to have resolved the issue on the other MacBook I have used for testing. Please confirm this has resolved the issue for you too.

**Comment by phenotypic** [comment]
Please follow issue #19 for CoreWLAN-related problems.
