### ISSUE TITLE
Location Services Authorization

### ISSUE THREAD

**Issue by LFavano** [phenotypic/WiFiCrackPy#18]
I'm getting the error `Unable to obtain authorisation, exiting...` shortly after running the code.

I know that Python must be granted Location Services access in order for it to work, but I can't manage to do that on MacOS 14.1.2, Python doesn't appear in my Location Services app list.

This is not strictly related to the code but do you perhaps have a solution to it?
Thanks

**Comment by raminsharifi** [comment]
same problem here

**Comment by phenotypic** [comment]
In the latest version of the script, I manually load the frameworks using `objc` rather than importing `CoreWLAN` and `CoreLocation` directly.

This seems to have resolved the issue on the other MacBook I have used for testing. Please confirm this has resolved the issue for you too.

**Comment by phenotypic** [comment]
For CoreWLAN-related bugs, please refer to issue #19. This includes network SSID/BSSIDs being displayed as `None`.

If you receive the `Unable to obtain authorisation, exiting...` error, ensure Python has been granted Location Services permissions by going to `System Settings` > `Privacy & Security` > `Location Services` and checking next to `Python`.

**Comment by northwestwitch** [comment]
Unfortunately I have this problem as well. MacOS version 14.1.2.

**Comment by 0nexx** [comment]
same problem. MacOS v.14.4.1
