### ISSUE TITLE
Not working with MAC

### ISSUE THREAD

**Issue by Zada5** [phenotypic/WiFiCrackPy#21]
output: 
"""
Obtaining authorisation for location services (required for WiFi scanning)...

error; Unable to obtain authorisation, exiting...
"""

**Comment by phenotypic** [comment]
For CoreWLAN-related bugs, please refer to issue #19.

If you receive the `Unable to obtain authorisation, exiting...` error, ensure Python has been granted Location Services permissions by going to `System Settings` > `Privacy & Security` > `Location Services` and checking next to `Python`.
