### ISSUE TITLE
Cracking

### ISSUE THREAD

**Issue by Plane3** [phenotypic/WiFiCrackPy#22]
Hi there,
I am having a really hard time figuring out what to do after I get to the : choose attack mode... nothing I try has worked, would it be possible for you to show us a sample script? I think I would understand a lot better then, also how do you pull the handshake directly from where it is stored? Or I guess more specifically at what point do you do that? Thank you.

**Comment by phenotypic** [comment]
Hi there, for `Dictionary` and `Brute-force` cracking you must have `hashcat` installed. Refer to the README for details on how to do this. If `Dictionary` is selected, you must also provide a word list.

Alternatively, you can manually run attacks against the `capture.hc22000` stored in the project folder.

For more details on how `hashcat` works and the various attack modes, please refer to the [hashcat wiki](https://hashcat.net/wiki/).
