### ISSUE TITLE
picks up 425497 packets and doesnt show me any information 

### ISSUE THREAD

**Issue by HenryDoesStuff** [phenotypic/WiFiCrackPy#26]
How long would this take? i gave it 30 mins. **this is my home wifi btw with wpa1**
![Screenshot 2024-07-11 at 5 35 15 PM](https://github.com/user-attachments/assets/b8ca546f-d3d7-4236-93b8-138e01a51b37)

**Comment by phenotypic** [comment]
Hi there, `zizzania` will continue capturing until a WPA handshake occurs on the target network (i.e. for a device to (re)connect).
