### ISSUE TITLE
CoreWLAN module not found

### ISSUE THREAD

**Issue by iRaccoon13** [phenotypic/WiFiCrackPy#30]
I've tried installing using pip, but it doesn't appear to be on PiPi.

**Comment by phenotypic** [comment]
Hi there, as per the README, please ensure you are installing the necessary Python dependencies: `pip3 install -r requirements.txt`

You should also make sure to follow the prerequisites section to resolve any other outstanding requirements.

**Comment by iRaccoon13** [comment]
I did!

**Comment by phenotypic** [comment]
CoreWLAN is found within the `PyObjC` library.

Run `pip3 install pyobjc`.

**Comment by iRaccoon13** [comment]
Oops! I had multiple versions of python installed, and pip and homebrew were fighting. I got it sorted out eventually.

**Comment by iRaccoon13** [comment]
It turns out I had multiple instances of python installed. Fixed!
