### ISSUE TITLE
Tutorial to Run, and some Bugs notes

### ISSUE THREAD

**Issue by EthanXu2010** [phenotypic/WiFiCrackPy#35]
Dear Phenotypic,
I hope this email finds you well. My name is Ethan Xu, and I have recently been using your WiFiCrackPy script. I appreciate the work you've done, and I wanted to take a moment to report a few issues I encountered as well as suggest some improvements that could enhance the user experience.

1. Error in Zizzania Command Execution
2. Handling of Invalid or Null BSSID
3. Skipping Mask Issue in Brute-force Mode

I added some code in my copy below that will skip the bugs in the code, and fix some other issues. 
THE CODE MIGHT NOT WORK BECAUSE THE DIRECTORY IS DIFFERENT

NOTES TO USERS.
    * I found giving location to the terminal to be complicated.
    * This report is targeted towards Mac Users
    * It would be beneficial to suggest that users run the script in Visual Studio Code (VSCode). Given that VSCode is widely used, especially among developers, it provides an excellent environment for running and debugging scripts.
    * Additionally, users should be instructed to grant location services permission for VSCode before running the script. This step is necessary for the WiFi scanning functionality to work correctly.
    * Instruct users to open the terminal in VSCode and grant necessary permissions by navigating to System Preferences > Security & Privacy > Privacy > Location Services, and then selecting VSCode from the list.
    * After setting up permissions, users should rerun the script from within VSCode.

Once again, thank you for your work on WiFiCrackPy. These suggestions and fixes aim to improve its robustness and usability. I would be happy to provide further insights or assist with testing any updates you might implement.
Best regards, Ethan Xu [Vancouver, British Columbia]

This is the code that worked for me (paste the setup.sh in the terminal, it can set things up and run the code):

[WiFiCrackPy.zip](https://github.com/user-attachments/files/16826322/WiFiCrackPy.zip)

DATE OF REPORT: 2024 Aug. 31

**Comment by EthanXu2010** [comment]
I managed to hack my own network, I got to say this is simple and easy to use, THANK YOU FOR THIS SCRIPT.

**Comment by phenotypic** [comment]
This issue has been closed due to suspicious activity. **Do not click the link or run the script as it may be harmful.**
