### ISSUE TITLE
No Name nor BSSID + NoneType not expected

### ISSUE THREAD

**Issue by MaxiZm** [phenotypic/WiFiCrackPy#37]
this is ran on sequia

Requesting authorisation for location services (required for WiFi scanning)...

Scanning for networks...

+--------+------+-------+------+---------+-------------------+
| Number | Name | BSSID | RSSI | Channel |      Security     |
+--------+------+-------+------+---------+-------------------+
|   1    | None |  None | -58  |    11   |   WPA2 Personal   |
|   2    | None |  None | -60  |    11   |   WPA2 Personal   |
|   3    | None |  None | -61  |    36   |   WPA2 Personal   |
|   4    | None |  None | -66  |    3    |   WPA2 Personal   |
|   5    | None |  None | -73  |    36   |   WPA2 Personal   |
|   6    | None |  None | -75  |    6    |   WPA2 Personal   |
|   7    | None |  None | -76  |    1    |   WPA2 Personal   |
|   8    | None |  None | -86  |   149   |   WPA2 Personal   |
|   9    | None |  None | -88  |    52   | WPA/WPA2 Personal |
+--------+------+-------+------+---------+-------------------+

Select a network to crack: 1

Initiating zizzania to capture handshake...

Traceback (most recent call last):
  File "/Users/mzalik/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/mzalik/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/mzalik/WiFiCrackPy/WiFiCrackPy.py", line 118, in capture_network
    subprocess.run(['sudo', zizzania_path, '-i', iface, '-b', bssid, '-w', 'capture.pcap', '-q'] + ['-n'] * args.d)
  File "/Users/mzalik/opt/miniconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/mzalik/opt/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/mzalik/opt/miniconda3/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by phenotypic** [comment]
Hi there, this is a compatibility issue listed in the project `README`.

For more information, please refer to issue #19.
