### ISSUE TITLE
AttributeError: 'CLLocationManager' object has no attribute 'authorizationStatus'

### ISSUE THREAD

**Issue by tormentous** [phenotypic/WiFiCrackPy#38]
macOS Catalina
10.15.17
Mid 2012

Followed all the steps.
I've allowed python for location services. whats wrong?

![Screen Shot 2024-09-30 at 1 41 19 PM](https://github.com/user-attachments/assets/fd684987-af7a-48bd-8921-a3272966af1a)

![Screen Shot 2024-09-30 at 1 41 08 PM](https://github.com/user-attachments/assets/031862b6-92ad-4da2-b865-a8b058e1252b)

**Comment by phenotypic** [comment]
Hi there, please ensure that you are running the latest version of macOS.

**Comment by tormentous** [comment]
Hi there, there is no more update available on this Machine.
