### ISSUE TITLE
Error after start

### ISSUE THREAD

**Issue by Pikman** [phenotypic/WiFiCrackPy#4]
I choose WPA network and then I receive this message:

Hash 'capture.hc22000': Separator unmatched
No hashes loaded.

Started: Wed Jan 25 16:54:39 2023
Stopped: Wed Jan 25 16:54:39 2023

**Comment by Pikman** [comment]
Installed zizzania properly, now it works!

**Comment by umbras** [comment]
Have the same problem, what was wrong and what did you change?

**Comment by Pikman** [comment]
> Have the same problem, what was wrong and what did you change?

install zizzania
