### ISSUE TITLE
wificrackpy issue with location permission macOS Catalina 

### ISSUE THREAD

**Issue by Bcharlit** [phenotypic/WiFiCrackPy#41]
Using MacBook Pro 15" Late 2008 on macOS Catalina 10.15.7 (with macOS Catalina Patcher)

After installing everything I got this error. It's probably related to location permission.
This is the issue
Traceback (most recent call last):
  File "/Users/charl/WiFiCrackPy/WiFiCrackPy.py", line 38, in <module>
    authorization_status = location_manager.authorizationStatus()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CLLocationManager' object has no attribute 'authorizationStatus'
'

when not closing the terminal after using "python3 WiFiCrackPy.py" and immediately using the command again, the script just returns:
AttributeError: 'CLLocationManager' object has no attribute 'authorizationStatus
'

**Comment by phenotypic** [comment]
Hi there, please ensure that you are running the latest version of macOS.

**Comment by tormentous** [comment]
you want us to update to the latest version of macos but this compatibility issue bothers us.

zizzania has the ability to send deauthentication frames to force a handshake. This feature is disabled by default as frame injection is not possible from macOS 12 (Monterey) onwards.
