### ISSUE TITLE
Pikman's Error

### ISSUE THREAD

**Issue by umbras** [phenotypic/WiFiCrackPy#6]
Hash 'capture.hc22000': Separator unmatched
No hashes loaded.

Started: Tue Jun 27 14:46:06 2023
Stopped: Tue Jun 27 14:46:06 2023

Pikman already had this error, but I also tried to reinstall and reclone zizzania, but it doesn't help.

**Comment by phenotypic** [comment]
In your terminal please run `~/zizzania/src/zizzania` and give the output.

**Comment by umbras** [comment]
zsh: no such file or directory

**Comment by phenotypic** [comment]
You've not installed `zizzania` correctly.

Ensure that the you are in the home directory (`cd /~`) before you clone `zizzania`.
