### ISSUE TITLE
Better documentation about pattern and Mode

### ISSUE THREAD

**Issue by Epizefiri** [phenotypic/WiFiCrackPy#7]
Hello there,
thanks for the tool :)

I don't know the difference between the modes ( Manual, Bruteforce, Dictionary ) and I didn't find any explanation of what the script means with "pattern"

It would be nice to have an explanation on the readme

**Comment by phenotypic** [comment]
Hi there, you can find more information on the core attack modes on the `hashcat` [wiki](https://hashcat.net/wiki/).

For more details on attack patterns, refer to the [mask attack](https://hashcat.net/wiki/doku.php?id=mask_attack) section.
