### ISSUE TITLE
How does it retain the handshake?

### ISSUE THREAD

**Issue by nahmanides** [phenotypic/WiFiCrackPy#8]
I've managed to get a handshake on one network and then failed to provide a wordlist using the dictionary method which caused the program to stop. Then I had to wait again to get that handshake for the same network. Have I misunderstood it completely?

**Comment by phenotypic** [comment]
Hi there, the handshake will be stored in the `capture.hc22000` file. You can attack this manually using `hashcat` from the command line even if the program has stopped. You can also select `Manual` attack when prompted by the script (option `3`)
